### ISSUE TITLE
edge case hell

### ISSUE THREAD

**Issue by NHQ** [projectsocrates/markdown-flavor-maker#4]
problems.  

If you parse for new brackets, and then run markdown on their insides (and then again over the whole text) you get funky html, for instance:

```hello ++world++```

will eval to ```hello <div><p>world</p>\n</div>\n```

...putting "world" in p tags, b/c it was markdown parsed alone (ie. marked('world'))

OTOH If you first parse for the new rules, replace the new brackets, and then parse markdown over the whole text once at the end, you miss the markdown inside your new rules altogether (if your new rules created html, as expected, which markdown ignores).  this however works if you only replace your new brackets with span tags (no divs of block tags), but then your span tags will get enclosed in p tags, by markdown,

Yet a third way is to parse the text for markdown first, then run it thru the bracketizer, but this results in p tags around your shit.

this:
```$--------```

becomes:
```<p><div class="comments">....</div></p>```

serviceable perhaps, but egde casey

**Comment by NHQ** [comment]
my feeling is the solution lies in restrictions or maybe some edge case params. 

like $------- would get "block":true
so you could parse markdown inside it
but ++ would get "block":false
so that its insides do not get parsed

**Comment by sartaj** [comment]
whatever your bracketize afterwards, could splice the string for the inveitble p tags?

**Comment by NHQ** [comment]
hm yeah maybe adding the inevitable p tags to the brackets

**Comment by sartaj** [comment]
`str.slice(2,str.length-4)`

**Comment by NHQ** [comment]
but no, how would I know when it's gonna get p tagged?

**Comment by sartaj** [comment]
new code fixes issues
